---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: gitlab
    type: deployer
    target:
      region_id: ibm:yp:us-south
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    script: |-
      #!/bin/bash
      echo "y" | bash deploy.sh
      cf push "${CF_APP}"

      # View logs
      #cf logs "${CF_APP}" --recent
